{% set python_min = '3.10' %}
{% set name = "flax" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f831350026ad48182ba6588bb4dd72dc1084985d9aca923254cb3e4c78d75f3

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - jax >=0.4.27
    - matplotlib-base
    - msgpack-python
    - numpy >=1.23.2
    - optax
    - orbax-checkpoint
    - tensorstore
    - rich >=11.1.0
    - typing_extensions >=4.2.0
    - pyyaml >=5.4.1

test:
  imports:
    - flax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/google/flax
  summary: 'Flax: A neural network library for JAX designed for flexibility'
  license: Apache-2.0
  license_file: LICENSE
  doc_url: http://flax.readthedocs.io
  dev_url: https://github.com/google/flax

extra:
  recipe-maintainers:
    - PhilipVinc
    - jheek
    - avital
    - levskaya
    - andsteing
    - gabrielcnr
    - traversaro
