{% set name = "flax" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8025607abc6077e29554af00996041454e89d10d6d2939d7cb4b86ecbc3fe360

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=3.10
    - jax >=0.4.27
    - matplotlib-base
    - msgpack-python
    - numpy >=1.23.2
    - optax
    - orbax-checkpoint
    - tensorstore
    - rich >=11.1.0
    - typing_extensions >=4.2.0
    - pyyaml >=5.4.1

test:
  imports:
    - flax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/flax
  summary: 'Flax: A neural network library for JAX designed for flexibility'
  license: Apache-2.0
  license_file: LICENSE
  doc_url: http://flax.readthedocs.io
  dev_url: https://github.com/google/flax

extra:
  recipe-maintainers:
    - PhilipVinc
    - jheek
    - avital
    - levskaya
    - andsteing
    - gabrielcnr
    - traversaro
